### ISSUE TITLE
Processing RS2 file seems buggy

### ISSUE THREAD

**Issue by Skealz** [umr-lops/grdwindinversion#35]
file : /home/datawork-cersat-public/cache/project/sarwing/data/RS2/L1/VV_VH/2022/248/RS2_OK141302_PK1242225_DK1208539_SCWA_20220905_212400_VV_VH_SGF

When processing this file I got not always the same output. Sometimes ncview bugs when displaying owiWindSpeed var, sometimes not.
It seems that for RS2 files there sometimes are artifacts in the wind speed var.

![rs2_1](https://github.com/umr-lops/grdwindinversion/assets/11155537/144b9eeb-8c56-4f9a-b6d8-359aa297de78)
![rs2_2](https://github.com/umr-lops/grdwindinversion/assets/11155537/af9c52be-bdcb-4a22-8721-62f098709b2a)

**Comment by Skealz** [comment]
The picture using 
![rs2_3](https://github.com/umr-lops/grdwindinversion/assets/11155537/1999ae4c-d2e2-4673-9d59-ea3258126546)
ncview when it successfully displays

**Comment by vincelhx** [comment]
here are my plots with my local .py 
 
files : 
```/home/datawork-cersat-public/cache/public/ftp/project/L2GRD/prod_v5/RS2_OK141302_PK1242225_DK1208539_SCWA_20220905_212400_VV_VH_SGF```
and ```/home/datawork-cersat-public/cache/public/ftp/project/L2GRD/prod_v5/RS2_OK141302_PK1242224_DK1208538_SCWA_20220905_212254_VV_VH_SGF```

![image](https://github.com/umr-lops/grdwindinversion/assets/38355798/c5f7c970-77b5-4cd3-8f82-0b649f2b9fea)
![image](https://github.com/umr-lops/grdwindinversion/assets/38355798/568282e5-3ba0-4dd8-90a0-40b95e0455a8)

**Comment by agrouaze** [comment]
after investigation with @vincelhx , the origin of the buggy fields for wind speed co and cross are related to `xsarsea` version.
issue to open in this repo.

**Comment by agrouaze** [comment]
working version (nice wind speed fields) for @vincelhx  using;
xsar                      0.9.7.dev164+g25db1e9           dev_0    <develop>
xsarsea                   0.3.dev122+ge1d9455           dev_0    <develop>

**Comment by agrouaze** [comment]
issue solved with https://github.com/umr-lops/xsarsea/pull/55
