### ISSUE TITLE
Add option to disable subdirectory creation

### ISSUE THREAD

**Issue by Skealz** [umr-lops/grdwindinversion#41]
When a netcdf is generated, a subdirectory is created (ie. S1A_IW_GRDH_1SDV_20230911T222130_20230911T222154_050286_060DC0_C12F.SAFE). It would be better if an option could enable/disable this behavior.

**Comment by agrouaze** [comment]
You suggest to remove the line https://github.com/umr-lops/grdwindinversion/blob/a6d2fb2fb9618a89315428cf91c81c8b13b7af4d/grdwindinversion/inversion.py#L455 ?
How would you track the original of a particular Level-1 measurement file?

**Comment by Skealz** [comment]
And I suggest making it an option, not removing it entirely !

**Comment by Skealz** [comment]
Fixed by https://github.com/umr-lops/grdwindinversion/commit/aab896367217f110788bf351f0a308ee084217c8
