### ISSUE TITLE
process HH files 

### ISSUE THREAD

**Issue by vincelhx** [umr-lops/grdwindinversion#50]
We can't process HH files ; 
https://github.com/umr-lops/xsarsea/blob/b12c73140137ba95197f8693c648c0e2d52bea67/src/xsarsea/windspeed/windspeed.py#L78

2 future solutions => 
- use VV GMF (cmod5n) 
- implement HH GMF

**Comment by agrouaze** [comment]
@vincelhx Can you recall which PR closed this issue?
